### ISSUE TITLE
Contributing documentation 

### ISSUE THREAD

**Issue by samzzzzzh** [DSCI-310/DSCI-310-Group-11#62]
Contributing documentation should reflect all the ways people can contribute to the project(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's,as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). -1

**Comment by Jaskaran1116** [comment]
The contributing document tells the external reader who can collaborate on this project. The updated version of the contributing file(after fixing the milestone issue) is [here](https://github.com/DSCI-310/DSCI-310-Group-11/blob/main/CONTRIBUTING.md). The older version of the contributing file can be found [here](https://github.com/DSCI-310/DSCI-310-Group-11/blob/1417a98f2244fbc1b3c4af6d58da35920a6823c2/CONTRIBUTING.md)
