### ISSUE TITLE
The example in `correlation_graph` is clearly incorrect. - 1

### ISSUE THREAD

**Issue by samzzzzzh** [DSCI-310/DSCI-310-Group-11#70]

**Comment by a-kong** [comment]
FIX: The output for `correlation_graph()` has been fixed. The code has been fixed to produce a correct `ggpairs()` output.

The associated code file:
[`correlation_graph.R`](https://github.com/DSCI-310/DSCI-310-Group-11-package/blob/235bdf82a982901f087af4e640dd128105d11091/R/correlation_graph.R#L20-L24)

The new output:
[`correlation_graph.png`](https://github.com/DSCI-310/DSCI-310-Group-11/blob/ad3a0eb339c743e58935ac314c3cb2c4f870a094/results/correlation_graph.png)

The old output:
[`correlation_graph.png`](https://github.com/DSCI-310/DSCI-310-Group-11/blob/3ca01051869ebd82654be4a7b0fc9fb5064236e5/results/correlation_graph.png)
